version: "3.9"

services:
  server:
    image: carlasim/carla:0.9.11
    entrypoint: ["/bin/bash", "/home/carla/CarlaUE4.sh"]
    command: [
      "-opengl",
      "-carla-rpc-port=${CARLA_SERVER_PORT:-2000}",
      "-carla-streaming-port=${CARLA_STREAMING_PORT:-2001}",
      "-quality-level=Epic"
    ]
    expose:
      - "${CARLA_SERVER_PORT:-2000}-${CARLA_STREAMING_PORT_2:-2002}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SDL_VIDEODRIVER: offscreen
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${CARLA_SERVER_GPU_ID:-0}']
              capabilities: ['compute','graphics','utility']
  client:
    build:
      context: pedestrians-video-2-carla
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: carla-pedestrians-client
        COMMIT: ${COMMIT}
    image: wielgoszinfo/carla-pedestrians-client:latest
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${OPENPOSE_DATASETS_PATH}:/datasets:ro
      - ${PWD}/pedestrians-video-2-carla:/app
      - vscode:/home/carla-pedestrians-client/.vscode-server
      - vscode-insiders:/home/carla-pedestrians-client/.vscode-server-insiders
      - outputs:/outputs
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
    shm_size: ${SHM_SIZE:-2gb}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${CLIENT_GPU_ID:-0}']
              capabilities: ['compute','graphics','utility']
    depends_on:
      - server

volumes: 
  vscode:
  vscode-insiders:
  outputs: