version: "3.9"

services:
  client:
    build:
      context: pedestrians-video-2-carla
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: carla-pedestrians-client
        COMMIT: ${COMMIT}
        PLATFORM: cpu
    image: wielgoszinfo/carla-pedestrians-client:latest
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${OPENPOSE_DATASETS_PATH}:/datasets:ro
      - ${PWD}/pedestrians-video-2-carla:/app
      - vscode:/home/carla-pedestrians-client/.vscode-server
      - vscode-insiders:/home/carla-pedestrians-client/.vscode-server-insiders
      - outputs:/outputs
      - ${RUNS_DIR_OR_VOLUME}:/runs
    shm_size: ${SHM_SIZE:-2gb}

volumes:
  vscode:
  vscode-insiders:
  outputs:
